#!/usr/bin/env bash
#
# Install everything!

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

fancy_echo() {
  echo "\n$1"
}

fancy_echo "Installing Homebrew ..."
  ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
  brew update

fancy_echo "Installing git ..."
  brew install git
  brew install git-flow

fancy_echo "Installing Postgres ..."
  brew install postgres --no-python
  initdb /usr/local/var/postgres -E utf8

fancy_echo "Installing Redis ..."
  brew install redis

fancy_echo "Installing vim ..."
  brew install vim

fancy_echo "Installing ImageMagick ..."
  brew install imagemagick

fancy_echo "Installing QT ..."
  brew install qt

fancy_echo "Installing GNU Compiler Collection ..."
  brew tap homebrew/dupes
  brew install apple-gcc42

fancy_echo "Upgrading and linking OpenSSL ..."
  brew install openssl

fancy_echo "Installing rvm ..."
  curl -L https://get.rvm.io | bash

fancy_echo "Installing lates Ruby 2.0.0 ..."
  rvm install 2.0.0
  rvm --default use 2.0.0
