#!/usr/bin/env bash
#
# Install everything!

trap 'ret=$?; test $ret -ne 0 && fail "$output"; exit $ret' EXIT

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n$2"
  echo ''
  exit
}

execute() {
  output=$($1 2>&1)
}

install_homebrew () {
  which -s brew
  if [ $? != 0 ]
  then
    info 'installing homebrew'
    execute 'ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)'
    execute 'brew update'
    success 'homebrew installed'
  else
    info 'updating homebrew'
    execute 'brew update'
    success 'homebrew updated'
  fi
}

install_homebrew

echo ''
echo 'All installed!'
